import{a as v,S as P,i}from"./assets/vendor-BK_rxH-O.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const q="51710897-f9d3bb10ca12010c1e23c8ef5",M="https://pixabay.com/api/";async function d(s,t=1){const n={key:q,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await v.get(M,{params:n})).data}const u=document.querySelector(".gallery"),m=document.querySelector(".loader"),f=document.querySelector(".load-more-btn"),B=new P(".gallery a",{captionsData:"alt",captionDelay:250});function h(s){const t=s.map(({webformatURL:n,largeImageURL:o,tags:e,likes:r,views:c,comments:w,downloads:S})=>`
      <li class="gallery-item">
        <a href="${o}">
          <img class="gallery-image" src="${n}" alt="${e}" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b> ${r}</p>
          <p class="info-item"><b>Views</b> ${c}</p>
          <p class="info-item"><b>Comments</b> ${w}</p>
          <p class="info-item"><b>Downloads</b> ${S}</p>
        </div>
      </li>
    `).join("");u.insertAdjacentHTML("beforeend",t),B.refresh()}function E(){u.innerHTML=""}function g(){m.classList.remove("hidden")}function p(){m.classList.add("hidden")}function y(){f.classList.remove("hidden")}function b(){f.classList.add("hidden")}const R=document.querySelector(".form"),$=document.querySelector(".load-more-btn");let l="",a=1;const L=15;R.addEventListener("submit",O);$.addEventListener("click",x);async function O(s){s.preventDefault();const t=s.currentTarget,n=t.elements["search-text"].value.trim();if(n===""){i.warning({title:"Warning",message:"Search input must not be empty!",position:"topRight"});return}l=n,a=1,E(),b(),g();try{const o=await d(l,a);if(o.hits.length===0)i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});else{h(o.hits);const e=Math.ceil(o.totalHits/L);a<e?y():i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}}catch(o){console.error(o),i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{p(),t.reset()}}async function x(){a+=1,b(),g();try{const s=await d(l,a);h(s.hits);const t=document.querySelector(".gallery-item");if(t){const o=t.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}const n=Math.ceil(s.totalHits/L);a<n?y():i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(s){console.error(s),i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{p()}}
//# sourceMappingURL=index.js.map
